########## FANCYPAGES SETTINGS
FP_HOMEPAGE_NAME = 'Home'
FP_DEFAULT_TEMPLATE = 'fancypages/pages/page.html'
########## END FANCYPAGES SETTINGS

########## TWITTER TAG SETTINGS
TWITTER_OAUTH_TOKEN = ''
TWITTER_OAUTH_SECRET = ''
TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
########## END TWITTER TAG SETTINGS

FANCYPAGES_SETTINGS = dict([(k, v) for k, v in locals().items()])
